spring:
  application:
    name: service-customer

server:
  port: 18001

management:
  server:
    port: 18101
  endpoints:
    web:
      exposure:
        include: "*"

#开启 Hystrix
feign:
  hystrix:
    enabled: true